apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-deployment
spec:
  replicas: 2 # Número de copias de tu app corriendo
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
      - name: node-app

        image: europe-west1-docker.pkg.dev/multi-services-488417/repo-multiservicios/mi-app:v1
        ports:
        - containerPort: 8080 # El puerto donde escucha tu Node.js
---
apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
spec:
  type: LoadBalancer # Esto te dará una IP pública para entrar desde el navegador
  selector:
    app: mi-app
  ports:
    - protocol: TCP
      port: 80 # Puerto externo
      targetPort: 3000 # Puerto interno de la app