apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
      - name: node-app
        # CAMBIO 1: Pon v1 (que es la que existe en tu consola)
        image: europe-west1-docker.pkg.dev/multi-services-488417/repo-multiservicios/mi-app:v3
        # CAMBIO 2: Baja los recursos para que quepa en el nodo (Insufficient memory)
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
        ports:
        - containerPort: 8080 # Tu index.js usa el 8080
        env:
        - name: DB_HOST
          value: "10.4.0.3"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "tu-password-seguro"
        - name: DB_NAME
          value: "db-app-principal"
---
apiVersion: v1
kind: Service
metadata:
  name: mi-app-service
spec:
  type: LoadBalancer
  selector:
    app: mi-app
  ports:
    - protocol: TCP
      port: 80
      # CAMBIO 3: targetPort debe ser 8080 (donde escucha Node)
      targetPort: 8080